services: 
  ocr:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  pgdata:
