services: 
  ocr:
    build: .
    command: python src/main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    restart: always
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:7
    ports:
      - "6383:6379"

  celery:
    build: .
    command: celery -A src.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  pgdata:
